import Head from "next/head";
import { Inter } from "@next/font/google";
import styles from "../styles/Home.module.css";
import Sections from "./../components/Sections/Sections";
import CenterSection from "./../components/CenterSection/CenterSection";
import CodePic from "../public/codePic.jpg";
import Image from "next/image";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  return (
    <>
      <Head>
        <title>Yara Brek</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.png" />
      </Head>
      <main className={styles.main}>
        <div className={styles.center}>
          <CenterSection></CenterSection>
        </div>
        <Image className={styles.img} src={CodePic} alt="CodePic" priority />
        <Sections></Sections>
      </main>
    </>
  );
}
