import Head from "next/head";
import styles from "../styles/Home.module.css";
import Sections from "./../components/Sections/Sections";
import CenterSection from "./../components/CenterSection/CenterSection";
import CodePic from "../public/codePic.jpg";
import Image from "next/image";
import { Container } from "../styles/GlobalComponents";

const Home = () => {
  return (
    <>
      <Head>
        <title>Yara Brek</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.png" />
      </Head>
      <Container>
          <CenterSection></CenterSection>
        <Image className={styles.img} src={CodePic} alt="CodePic" priority />
        <Sections></Sections>
      </Container>
    </>
  );
}

export default Home  